platform :ios, '8.0'
source 'ssh://git@git.sankuai.com/ios/specs.git'

target 'EasyMVVM_Example' do
  use_frameworks!
  pod 'EasyMVVM', :path => '../'
  
  target 'EasyMVVM_ExampleTests' do
    inherit! :search_paths
    pod 'Quick', '~>1.1.0'
    pod 'Nimble', '~>7.0.1'
    pod 'OCMock'
  end
  
  target 'EasyMVVM_ExampleUITests' do
      inherit! :search_paths
      pod 'Quick', '~>1.1.0'
      pod 'Nimble', '~>7.0.1'
  end
end

