platform :ios, '8.0'

target 'EasyMVVM_Example' do
  use_frameworks!
  pod 'EasyMVVM', :path => '../'
  pod 'Masonry'
  target 'EasyMVVM_ExampleTests' do
    use_frameworks!
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
    pod 'OCMock'
  end
  
  target 'EasyMVVM_ExampleUITests' do
      use_frameworks!
      inherit! :search_paths
      pod 'Quick'
      pod 'Nimble'
  end
end

